// Hardware-free proof of the derived (label-based) X-Wing split-custody
// crypto (src/onlykey-fido2/onlykey/age_pqc.js) - the maintainer's TC-08
// ("npm run test:pqc"): mirrors python-onlykey's tests/test_derived_xwing.py
// 1:1 (5 tests) plus a 6th cross-implementation check against a fixed
// vector generated by the real Python reference. No device, no FIDO2:
// deviceDerive() below is a stand-in that generates a random X25519 key
// locally, exactly like the Python test's _device_derive() and this app's
// own onlykey-testing twin (test/05-age-pqc-derived.test.js) - wiring to the
// real device is separate, already-proven work (see TEST-PLAN.md TC-09/10,
// TC-18/19).
//
// No test framework here on purpose - this app doesn't carry one, and
// adding mocha/jest just for this one hardware-free suite isn't worth a new
// devDependency. Built through webpack (see package.json's "test:pqc"
// script) only because age_pqc.js's @noble/* bare specifiers need the
// existing resolve.alias to resolve - plain `node test/pqc.test.js` won't
// work without that.
const assert = require('assert');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const { x25519 } = require('@noble/curves/ed25519.js');
const agePqc = require('../src/onlykey-fido2/onlykey/age_pqc.js');

function deviceDerive() {
    const skX = x25519.utils.randomSecretKey();
    const pkX = x25519.getPublicKey(skX);
    const mlkemSeed = crypto.randomBytes(32);
    return { skX, pkX, mlkemSeed };
}

const tests = [];
function test(name, fn) {
    tests.push({ name, fn });
}

test('recipient is 1216 bytes', () => {
    const { pkX, mlkemSeed } = deviceDerive();
    assert.strictEqual(agePqc.buildRecipient(pkX, mlkemSeed).length, 1216);
});

test('split decaps matches standard encaps', () => {
    const { skX, pkX, mlkemSeed } = deviceDerive();
    const recipient = agePqc.buildRecipient(pkX, mlkemSeed);

    const { sharedSecret: ssEnc, ciphertext: ct } = agePqc.xwingEncapsHost(recipient);
    assert.strictEqual(ct.length, 1120);

    const ssX = x25519.getSharedSecret(skX, agePqc.ctXOf(ct)); // device: X25519(sk_X, ct_X)
    const ssDec = agePqc.splitDecapsulate(ssX, ct, pkX, mlkemSeed); // host: ML-KEM half + combiner
    assert.deepStrictEqual(Buffer.from(ssDec), Buffer.from(ssEnc));
});

test('wrong device share fails ("no device => no decrypt")', () => {
    const { pkX, mlkemSeed } = deviceDerive();
    const recipient = agePqc.buildRecipient(pkX, mlkemSeed);
    const { sharedSecret: ssEnc, ciphertext: ct } = agePqc.xwingEncapsHost(recipient);
    const bad = agePqc.splitDecapsulate(new Uint8Array(32), ct, pkX, mlkemSeed); // no device ss_X
    assert.notDeepStrictEqual(Buffer.from(bad), Buffer.from(ssEnc));
});

test('deterministic recipient per seed', () => {
    const { pkX, mlkemSeed } = deviceDerive();
    assert.deepStrictEqual(
        Buffer.from(agePqc.buildRecipient(pkX, mlkemSeed)),
        Buffer.from(agePqc.buildRecipient(pkX, mlkemSeed))
    );
});

test('derived identity roundtrip', () => {
    for (const label of ['age:personal', 'alice@example.com', 'work']) {
        const ident = agePqc.encodeIdentity(label);
        // Real bech32 now (age-plugin-onlykey-1..., the SAME HRP slot
        // identities use), not the old stale AGE-PLUGIN-ONLYKEY-DERIVED-
        // scheme - see age_pqc.js's own doc comment for why.
        assert.ok(ident.startsWith('AGE-PLUGIN-ONLYKEY-1'));
        assert.deepStrictEqual(agePqc.decodeIdentity(ident), { derived: true, label });
    }
    // Garbage input decodes to null (bad bech32 checksum) rather than throwing.
    assert.strictEqual(agePqc.decodeIdentity('not-a-bech32-string'), null);
});

// Beyond the 5 self-consistency checks above (mirroring
// test_derived_xwing.py 1:1): this fixture was generated by
// onlykey-testing/lib/py/gen_derived_xwing_vector.py running the actual
// Python reference (derived_xwing.py + xwing.py) on fixed inputs, so this
// proves the JS port isn't just internally consistent with itself - it's
// byte-for-byte identical to what the CLI actually computes.
test('matches python-onlykey derived_xwing.py byte-for-byte (fixed vector)', () => {
    // process.cwd(), not __dirname - webpack's node target mocks __dirname
    // to a fake path by default, but `npm run test:pqc` always runs from
    // this package's root, so cwd is a reliable anchor instead.
    const vectorPath = path.join(process.cwd(), 'test', 'fixtures', 'derived-xwing-vector.json');
    const v = JSON.parse(fs.readFileSync(vectorPath, 'utf8'));
    const b64 = (s) => Buffer.from(s, 'base64');

    const pkX = b64(v.pk_x);
    const mlkemSeed = b64(v.mlkem_seed);
    const ssX = b64(v.ss_x);
    const ciphertext = b64(v.ciphertext);

    const { publicKey: pkM } = agePqc.mlkemKeypairFromSeed(mlkemSeed);
    assert.deepStrictEqual(Buffer.from(pkM), b64(v.pk_m), 'pk_M mismatch vs python');

    const recipient = agePqc.buildRecipient(pkX, mlkemSeed);
    assert.deepStrictEqual(Buffer.from(recipient), b64(v.recipient), 'recipient mismatch vs python');

    assert.deepStrictEqual(Buffer.from(agePqc.ctXOf(ciphertext)), b64(v.ct_x), 'ct_X mismatch vs python');

    const ssDec = agePqc.splitDecapsulate(ssX, ciphertext, pkX, mlkemSeed);
    assert.deepStrictEqual(Buffer.from(ssDec), b64(v.shared_secret), 'shared secret mismatch vs python');
});

let pass = 0;
let fail = 0;
for (const { name, fn } of tests) {
    try {
        fn();
        pass++;
        console.log(`  ok - ${name}`);
    } catch (e) {
        fail++;
        console.log(`  FAIL - ${name}: ${e.message}`);
    }
}
console.log(`pass ${pass}, fail ${fail}`);
if (fail > 0) process.exitCode = 1;
