// GENERATED by libraries/onlykey/protocol/gen.py from onlykey-protocol.json - DO NOT EDIT
// OnlyKey host<->device protocol constants (protocol_version 1).
// Works as a CommonJS module (OnlyKey-App / node) and as a webpack import (web app).
(function (root, factory) {
  if (typeof module === 'object' && module.exports) { module.exports = factory(); }
  else { root.OnlyKeyProtocol = factory(); }
}(typeof self !== 'undefined' ? self : this, function () {
  'use strict';
  var P = {};
  P.PROTOCOL_VERSION = 1;

  // Message ids (first byte after the 0xFF x4 header). Firmware macro names + host aliases.
  P.OKCMD = {
    OKPIN: 225,
    OKPINSD: 226,
    OKPINSEC: 227,
    OKCONNECT: 228, // sets time + opens the session; the web app's FIDO2 requests all ride on this cmd
    OKGETLABELS: 229, // buffer[5]: 'k' key labels, 'c' capabilities, else slot labels
    OKSETSLOT: 230,
    OKWIPESLOT: 231,
    OKSETU2FPRIV: 232, // deprecated
    OKWIPEU2FPRIV: 233, // deprecated
    OKSETU2FCERT: 234, // deprecated
    OKWIPEU2FCERT: 235, // deprecated
    OKGETPUBKEY: 236,
    OKSIGN: 237,
    OKWIPEPRIV: 238,
    OKSETPRIV: 239,
    OKDECRYPT: 240,
    OKRESTORE: 241,
    OKGETRESPONSE: 242,
    OKPING: 243,
    OKFWUPDATE: 244, // NEVER send to a developer key: converts it to production
    OKHMAC: 245,
    OKWEBAUTHN: 246,
    OKSETPIN: 225, // alias of OKPIN
    OKSETSDPIN: 226, // alias of OKPINSD
    OKSETPDPIN: 227, // alias of OKPINSEC
    OKSETPIN2: 227, // alias of OKPINSEC
    OKSETTIME: 228, // alias of OKCONNECT
  };

  // OKSETSLOT field ids (buffer[6]).
  P.FIELD = {
    LABEL: 1, // slot
    USERNAME: 2, // slot
    NEXTKEY2: 3, // slot
    DELAY2: 4, // slot
    PASSWORD: 5, // slot
    NEXTKEY3: 6, // slot
    DELAY3: 7, // slot
    TFATYPE: 8, // slot
    TOTPKEY: 9, // slot
    YUBIAUTH: 10, // slot
    IDLETIMEOUT: 11, // setting
    WIPEMODE: 12, // setting
    KEYTYPESPEED: 13, // setting
    KEYLAYOUT: 14, // setting
    URL: 15, // slot
    NEXTKEY1: 16, // slot
    DELAY1: 17, // slot
    NEXTKEY4: 18, // slot
    NEXTKEY5: 19, // slot
    BACKUPKEYMODE: 20, // setting
    DERIVEDKEYMODE: 21, // setting
    STOREDKEYMODE: 22, // setting
    SECPROFILEMODE: 23, // setting
    LEDBRIGHTNESS: 24, // setting
    LOCKBUTTON: 25, // setting
    HMACMODE: 26, // setting
    SYSADMINMODE: 27, // setting
    TOUCHSENSE: 28, // setting
    YUBIANDHMAC: 29, // slot
    WEBDERIVEMODE: 30, // setting
    TFAUSERNAME: 9, // alias of TOTPKEY
    LOCKOUT: 11, // alias of IDLETIMEOUT
    TYPESPEED: 13, // alias of KEYTYPESPEED
    KBDLAYOUT: 14, // alias of KEYLAYOUT
    BACKUPMODE: 20, // alias of BACKUPKEYMODE
    SSHCHALENGEMODE: 21, // alias of DERIVEDKEYMODE
    derivedchallengeMode: 21, // alias of DERIVEDKEYMODE
    PGPCHALENGEMODE: 22, // alias of STOREDKEYMODE
    storedchallengeMode: 22, // alias of STOREDKEYMODE
    SECONDPROFILEMODE: 23, // alias of SECPROFILEMODE
    hmacchallengeMode: 26, // alias of HMACMODE
    modkeyMode: 27, // alias of SYSADMINMODE
    webderiveMode: 30, // alias of WEBDERIVEMODE
  };
  P.SETTING_FIELDS = [11, 12, 13, 14, 20, 21, 22, 23, 24, 25, 26, 27, 28, 30];
  // field id -> 'any' | 'config_mode' | 'first_init' (when the setting may be written)
  P.FIELD_WRITABLE = { 11: 'any', 12: 'first_init', 13: 'any', 14: 'any', 20: 'first_init', 21: 'config_mode', 22: 'config_mode', 23: 'first_init', 24: 'any', 25: 'any', 26: 'config_mode', 27: 'config_mode', 28: 'config_mode', 30: 'config_mode' };

  P.USER_INPUT_MODE = { CHALLENGE_CODE: 0, BUTTON_PRESS: 1, NO_PRESS: 2 };
  P.USER_INPUT_MODE_DEFAULTS = { DERIVEDKEYMODE: 1, STOREDKEYMODE: 1, WEBDERIVEMODE: 1 };
  // NO_PRESS on these fields needs firmware built with OK_ALLOW_NO_PRESS (see capabilities flag NO_PRESS_ALLOWED).
  P.NO_PRESS_GATED_FIELDS = [P.FIELD.DERIVEDKEYMODE, P.FIELD.STOREDKEYMODE];

  // Key type ids (low nibble of key_type byte) for ECC/PQC slots 101-132.
  P.KEYTYPE = {
    ED25519: 1,
    P256R1: 2,
    P256K1: 3,
    CURVE25519: 4,
    MLKEM768: 5,
    XWING: 6,
    PQC_PGP: 7,
    HMACSHA1: 9,
    NACL: 1, // alias of ED25519
    NIST256P1: 2, // alias of P256R1
    P256: 2, // alias of P256R1
    SECP256K1: 3, // alias of P256K1
    X25519: 4, // alias of CURVE25519
    COMPOSITE: 7, // alias of PQC_PGP
  };
  P.KEYTYPE_NAMES = ['ED25519', 'P256R1', 'P256K1', 'CURVE25519', 'MLKEM768', 'XWING', 'PQC_PGP', 'HMACSHA1']; // canonical names only (no aliases)
  // What the FIDO2 web app sends as opt2 (firmware does opt2++): id - 1.
  P.KEYTYPE_WEB_WIRE = {
    ED25519: 0,
    P256R1: 1,
    P256K1: 2,
    CURVE25519: 3,
    MLKEM768: 4,
    XWING: 5,
  };
  P.KEYTYPE_OPS = {
    1: ['sign'],
    2: ['sign', 'decrypt'],
    3: ['sign', 'decrypt'],
    4: ['decrypt'],
    5: ['decrypt'],
    6: ['decrypt'],
    7: ['sign', 'decrypt'],
    9: ['hmac'],
  };
  P.KEY_FEATURE = { DECRYPT: 32, SIGN: 64, BACKUP: 128 };
  P.RESERVED_SLOT = { WEB_DERIVATION: 128, HMACSHA1_2: 129, HMACSHA1_1: 130, DEFAULT_BACKUP: 131, DERIVATION: 132, DERIVATION_V2: 232 };
  P.DERIVE_ACTION = { DERIVE_PUBLIC_KEY: 1, DERIVE_SHARED_SECRET: 2, DERIVE_PUBLIC_KEY_REQ_PRESS: 3, DERIVE_SHARED_SECRET_REQ_PRESS: 4 };
  // SSH/GPG agent derivation codes: v1 = released SHA256 KDF, v2 = HKDF
  P.AGENT_DERIVATION = {
    v1: { pubkey_slot: 132, sign: { ED25519: 201, P256R1: 202, P256K1: 203 }, decrypt: { P256R1: 202, P256K1: 203, CURVE25519: 204 } },
    v2: { pubkey_slot: 232, sign: { ED25519: 221, P256R1: 222, P256K1: 223 }, decrypt: { P256R1: 222, P256K1: 223, CURVE25519: 224 } },
  };

  P.CHALLENGE_INDICES = [0, 15, 31];
  P.CHALLENGE_MODULUS = 6;
  P.CHALLENGE_MODULUS_DUO = 3;
  // hash: the SHA-256 digest (Uint8Array/Array) of the exact payload the device hashes.
  P.challengeCodeFromHash = function (hash, duo) {
    var mod = duo ? P.CHALLENGE_MODULUS_DUO : P.CHALLENGE_MODULUS;
    return P.CHALLENGE_INDICES.map(function (i) { return (hash[i] % mod) + 1; });
  };
  // payload: the bytes the device hashes; returns a Promise of [b1,b2,b3] (WebCrypto).
  P.challengeCode = function (payload, duo) {
    var subtle = (typeof crypto !== 'undefined' && crypto.subtle) || (typeof window !== 'undefined' && window.crypto && window.crypto.subtle);
    if (!subtle) { throw new Error('WebCrypto not available'); }
    return subtle.digest('SHA-256', Uint8Array.from(payload)).then(function (h) {
      return P.challengeCodeFromHash(new Uint8Array(h), duo);
    });
  };

  P.ERROR_PREFIXES = ['Error', 'ERROR', 'Timeout'];
  P.SUCCESS_PREFIXES = ['Successfully', 'UNLOCKED', 'INITIALIZED', 'UNINITIALIZED', 'No PIN set'];
  P.KNOWN_RESPONSE = {
    NOT_IN_CONFIG_MODE: 'Error not in config mode',
    CONFIG_MODE_NOT_SUPPORTED: 'ERROR NOT SUPPORTED IN CONFIG MODE',
    DEVICE_LOCKED: 'Error device locked',
    WRONG_CHALLENGE: 'Error incorrect challenge was entered',
    CONFIRMATION_WINDOW_CLOSED: 'Error confirmation window closed before the button was pressed',
    PRESS_NOT_ACCEPTED: 'Error button press was not accepted',
    CONFIRMATION_TIMEOUT: 'Timeout occured while waiting for confirmation on OnlyKey',
    NO_KEY_IN_SLOT: 'Error no key set in this slot',
    INVALID_USER_INPUT_MODE: 'Error invalid user input mode',
    UNSUPPORTED_USER_INPUT_MODE: 'Error unsupported user input mode',
    LOCKED: 'INITIALIZED',
    UNINITIALIZED: 'UNINITIALIZED',
    NO_PIN: 'No PIN set, You must set a PIN first',
    SECPROFILE_FIRST_INIT_ONLY: 'Error Second Profile Mode may only be changed on first use',
    WIPE_MODE_LOCKED: 'Error Wipe Mode may not be changed',
    BACKUP_KEY_MODE_LOCKED: 'Error Backup Key Mode may not be changed',
    DERIVED_REQUEST_WRONG_SIZE: 'Error derived key request wrong size',
    DERIVED_KEY_TYPE_UNSUPPORTED: 'Error unsupported derived key type',
    PD_RETIRED: 'Error plausible deniability profile is no longer supported',
  };
  function startsWithAscii(bytes, s) {
    if (bytes.length < s.length) return false;
    for (var i = 0; i < s.length; i++) { if (bytes[i] !== s.charCodeAt(i)) return false; }
    return true;
  }
  function asciiUntilNul(bytes) {
    var s = '';
    for (var i = 0; i < bytes.length && bytes[i] !== 0; i++) { s += String.fromCharCode(bytes[i]); }
    return s;
  }
  // Classify a raw device report: {kind:'error'|'status'|'data', text?, data?}.
  P.classifyResponse = function (bytes) {
    bytes = Uint8Array.from(bytes);
    var i;
    for (i = 0; i < P.ERROR_PREFIXES.length; i++) {
      if (startsWithAscii(bytes, P.ERROR_PREFIXES[i])) return { kind: 'error', text: asciiUntilNul(bytes) };
    }
    for (i = 0; i < P.SUCCESS_PREFIXES.length; i++) {
      if (startsWithAscii(bytes, P.SUCCESS_PREFIXES[i])) return { kind: 'status', text: asciiUntilNul(bytes) };
    }
    return { kind: 'data', data: bytes };
  };
  P.isError = function (bytes) { return P.classifyResponse(bytes).kind === 'error'; };

  // Derived keys over raw HID (slot 128): [cmd][slot][len|0xFF][keytype][label32][ct_X32?]
  P.DERIVED_RECIPIENT_LEN = 33;
  P.DERIVED_DECAPS_LEN = 65;

  P.CAPABILITIES_MAGIC = 202;
  P.CAPABILITIES_SELECTOR = 'c'.charCodeAt(0); // OKGETLABELS buffer[5]
  P.CAPABILITY_FLAG = { NO_PRESS_ALLOWED: 1, DEBUG_BUILD: 2, DUO: 4, PQC: 8, HKDF_V2_DERIVATION: 16 };
  // Parse the 64-byte capabilities report; null if the firmware does not send one.
  P.parseCapabilities = function (bytes) {
    bytes = Uint8Array.from(bytes);
    if (bytes.length < 64 || bytes[0] !== P.CAPABILITIES_MAGIC) return null;
    var out = {};
    out.protocol_version = bytes[1];
    out.fw_major = bytes[2];
    out.fw_minor = bytes[3];
    out.fw_patch = bytes[4];
    var mask = bytes[5] | (bytes[6] << 8);
    out.key_types = P.KEYTYPE_NAMES.filter(function (k) { return mask & (1 << P.KEYTYPE[k]); });
    out.flags = Object.keys(P.CAPABILITY_FLAG).filter(function (k) { return bytes[7] & P.CAPABILITY_FLAG[k]; });
    out.version = asciiUntilNul(bytes.subarray(8, 64));
    out.no_press_allowed = out.flags.indexOf('NO_PRESS_ALLOWED') >= 0;
    return out;
  };

  return P;
}));
